-- MySQL Script generated by MySQL Workbench
-- Tue Jun  7 00:07:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 2GoMobile
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 2GoMobile
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `2GoMobile` DEFAULT CHARACTER SET utf8 ;
USE `2GoMobile` ;

-- -----------------------------------------------------
-- Table `2GoMobile`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2GoMobile`.`departamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2GoMobile`.`projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2GoMobile`.`projetos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `prazo_final` DATETIME NOT NULL,
  `departamento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `projetos_1_idx` (`departamento_id` ASC) VISIBLE,
  CONSTRAINT `projetos_1`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `2GoMobile`.`departamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2GoMobile`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2GoMobile`.`funcionarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `cargo` VARCHAR(50) NOT NULL,
  `data_contratacao` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2GoMobile`.`dependentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2GoMobile`.`dependentes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `funcionario_id` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `grau_parentesco` VARCHAR(50) NOT NULL,
  `data_nascimento` DATETIME NOT NULL,
  `sexo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `dependente_1_idx` (`funcionario_id` ASC) VISIBLE,
  CONSTRAINT `dependente_1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `2GoMobile`.`funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2GoMobile`.`funcionario_projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2GoMobile`.`funcionario_projeto` (
  `funcionario_id` INT NOT NULL,
  `projeto_id` INT NOT NULL,
  INDEX `funcionario_projeto_1_idx` (`funcionario_id` ASC) VISIBLE,
  INDEX `funcionario_projeto_2_idx` (`projeto_id` ASC) VISIBLE,
  CONSTRAINT `funcionario_projeto_1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `2GoMobile`.`funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `funcionario_projeto_2`
    FOREIGN KEY (`projeto_id`)
    REFERENCES `2GoMobile`.`projetos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
